spring.application.name=demo
spring.data.mongodb.uri=mongodb+srv://admin:Avengers@cluster0.utfduvi.mongodb.net/recipe_db?appName=Cluster0
spring.data.mongodb.database=recipe_db
server.port=${PORT:8080}